package com.mydb.common.nio;


// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IOMsg.proto

@SuppressWarnings({"unused","unchecked"})
public final class IOMsgOuterClass {
  private IOMsgOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface IOMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IOMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>sint32 CMD = 1;</code>
     */
    int getCMD();

    /**
     * <code>sint32 TYPE = 2;</code>
     */
    int getTYPE();

    /**
     * <code>sint32 STATUS = 3;</code>
     */
    int getSTATUS();

    /**
     * <code>string BODY = 4;</code>
     */
    java.lang.String getBODY();
    /**
     * <code>string BODY = 4;</code>
     */
    com.google.protobuf.ByteString
        getBODYBytes();

    /**
     * <code>string DES = 5;</code>
     */
    java.lang.String getDES();
    /**
     * <code>string DES = 5;</code>
     */
    com.google.protobuf.ByteString
        getDESBytes();
  }
  /**
   * Protobuf type {@code IOMsg}
   */
  public  static final class IOMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:IOMsg)
      IOMsgOrBuilder {
    // Use IOMsg.newBuilder() to construct.
    private IOMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IOMsg() {
      cMD_ = 0;
      tYPE_ = 0;
      sTATUS_ = 0;
      bODY_ = "";
      dES_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private IOMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              cMD_ = input.readSInt32();
              break;
            }
            case 16: {

              tYPE_ = input.readSInt32();
              break;
            }
            case 24: {

              sTATUS_ = input.readSInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              bODY_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              dES_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return IOMsgOuterClass.internal_static_IOMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return IOMsgOuterClass.internal_static_IOMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              IOMsgOuterClass.IOMsg.class, IOMsgOuterClass.IOMsg.Builder.class);
    }

    public static final int CMD_FIELD_NUMBER = 1;
    private int cMD_;
    /**
     * <code>sint32 CMD = 1;</code>
     */
    public int getCMD() {
      return cMD_;
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int tYPE_;
    /**
     * <code>sint32 TYPE = 2;</code>
     */
    public int getTYPE() {
      return tYPE_;
    }

    public static final int STATUS_FIELD_NUMBER = 3;
    private int sTATUS_;
    /**
     * <code>sint32 STATUS = 3;</code>
     */
    public int getSTATUS() {
      return sTATUS_;
    }

    public static final int BODY_FIELD_NUMBER = 4;
    private volatile java.lang.Object bODY_;
    /**
     * <code>string BODY = 4;</code>
     */
    public java.lang.String getBODY() {
      java.lang.Object ref = bODY_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bODY_ = s;
        return s;
      }
    }
    /**
     * <code>string BODY = 4;</code>
     */
    public com.google.protobuf.ByteString
        getBODYBytes() {
      java.lang.Object ref = bODY_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bODY_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DES_FIELD_NUMBER = 5;
    private volatile java.lang.Object dES_;
    /**
     * <code>string DES = 5;</code>
     */
    public java.lang.String getDES() {
      java.lang.Object ref = dES_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dES_ = s;
        return s;
      }
    }
    /**
     * <code>string DES = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDESBytes() {
      java.lang.Object ref = dES_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dES_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (cMD_ != 0) {
        output.writeSInt32(1, cMD_);
      }
      if (tYPE_ != 0) {
        output.writeSInt32(2, tYPE_);
      }
      if (sTATUS_ != 0) {
        output.writeSInt32(3, sTATUS_);
      }
      if (!getBODYBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, bODY_);
      }
      if (!getDESBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, dES_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (cMD_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(1, cMD_);
      }
      if (tYPE_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(2, tYPE_);
      }
      if (sTATUS_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(3, sTATUS_);
      }
      if (!getBODYBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, bODY_);
      }
      if (!getDESBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, dES_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof IOMsgOuterClass.IOMsg)) {
        return super.equals(obj);
      }
      IOMsgOuterClass.IOMsg other = (IOMsgOuterClass.IOMsg) obj;

      boolean result = true;
      result = result && (getCMD()
          == other.getCMD());
      result = result && (getTYPE()
          == other.getTYPE());
      result = result && (getSTATUS()
          == other.getSTATUS());
      result = result && getBODY()
          .equals(other.getBODY());
      result = result && getDES()
          .equals(other.getDES());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CMD_FIELD_NUMBER;
      hash = (53 * hash) + getCMD();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getTYPE();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getSTATUS();
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBODY().hashCode();
      hash = (37 * hash) + DES_FIELD_NUMBER;
      hash = (53 * hash) + getDES().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static IOMsgOuterClass.IOMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static IOMsgOuterClass.IOMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static IOMsgOuterClass.IOMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static IOMsgOuterClass.IOMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static IOMsgOuterClass.IOMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static IOMsgOuterClass.IOMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static IOMsgOuterClass.IOMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static IOMsgOuterClass.IOMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static IOMsgOuterClass.IOMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static IOMsgOuterClass.IOMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(IOMsgOuterClass.IOMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code IOMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:IOMsg)
        IOMsgOuterClass.IOMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return IOMsgOuterClass.internal_static_IOMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return IOMsgOuterClass.internal_static_IOMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                IOMsgOuterClass.IOMsg.class, IOMsgOuterClass.IOMsg.Builder.class);
      }

      // Construct using IOMsgOuterClass.IOMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        cMD_ = 0;

        tYPE_ = 0;

        sTATUS_ = 0;

        bODY_ = "";

        dES_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return IOMsgOuterClass.internal_static_IOMsg_descriptor;
      }

      public IOMsgOuterClass.IOMsg getDefaultInstanceForType() {
        return IOMsgOuterClass.IOMsg.getDefaultInstance();
      }

      public IOMsgOuterClass.IOMsg build() {
        IOMsgOuterClass.IOMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public IOMsgOuterClass.IOMsg buildPartial() {
        IOMsgOuterClass.IOMsg result = new IOMsgOuterClass.IOMsg(this);
        result.cMD_ = cMD_;
        result.tYPE_ = tYPE_;
        result.sTATUS_ = sTATUS_;
        result.bODY_ = bODY_;
        result.dES_ = dES_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof IOMsgOuterClass.IOMsg) {
          return mergeFrom((IOMsgOuterClass.IOMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(IOMsgOuterClass.IOMsg other) {
        if (other == IOMsgOuterClass.IOMsg.getDefaultInstance()) return this;
        if (other.getCMD() != 0) {
          setCMD(other.getCMD());
        }
        if (other.getTYPE() != 0) {
          setTYPE(other.getTYPE());
        }
        if (other.getSTATUS() != 0) {
          setSTATUS(other.getSTATUS());
        }
        if (!other.getBODY().isEmpty()) {
          bODY_ = other.bODY_;
          onChanged();
        }
        if (!other.getDES().isEmpty()) {
          dES_ = other.dES_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        IOMsgOuterClass.IOMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (IOMsgOuterClass.IOMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int cMD_ ;
      /**
       * <code>sint32 CMD = 1;</code>
       */
      public int getCMD() {
        return cMD_;
      }
      /**
       * <code>sint32 CMD = 1;</code>
       */
      public Builder setCMD(int value) {
        
        cMD_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sint32 CMD = 1;</code>
       */
      public Builder clearCMD() {
        
        cMD_ = 0;
        onChanged();
        return this;
      }

      private int tYPE_ ;
      /**
       * <code>sint32 TYPE = 2;</code>
       */
      public int getTYPE() {
        return tYPE_;
      }
      /**
       * <code>sint32 TYPE = 2;</code>
       */
      public Builder setTYPE(int value) {
        
        tYPE_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sint32 TYPE = 2;</code>
       */
      public Builder clearTYPE() {
        
        tYPE_ = 0;
        onChanged();
        return this;
      }

      private int sTATUS_ ;
      /**
       * <code>sint32 STATUS = 3;</code>
       */
      public int getSTATUS() {
        return sTATUS_;
      }
      /**
       * <code>sint32 STATUS = 3;</code>
       */
      public Builder setSTATUS(int value) {
        
        sTATUS_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sint32 STATUS = 3;</code>
       */
      public Builder clearSTATUS() {
        
        sTATUS_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object bODY_ = "";
      /**
       * <code>string BODY = 4;</code>
       */
      public java.lang.String getBODY() {
        java.lang.Object ref = bODY_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          bODY_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string BODY = 4;</code>
       */
      public com.google.protobuf.ByteString
          getBODYBytes() {
        java.lang.Object ref = bODY_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bODY_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string BODY = 4;</code>
       */
      public Builder setBODY(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        bODY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string BODY = 4;</code>
       */
      public Builder clearBODY() {
        
        bODY_ = getDefaultInstance().getBODY();
        onChanged();
        return this;
      }
      /**
       * <code>string BODY = 4;</code>
       */
      public Builder setBODYBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        bODY_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object dES_ = "";
      /**
       * <code>string DES = 5;</code>
       */
      public java.lang.String getDES() {
        java.lang.Object ref = dES_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dES_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string DES = 5;</code>
       */
      public com.google.protobuf.ByteString
          getDESBytes() {
        java.lang.Object ref = dES_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dES_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string DES = 5;</code>
       */
      public Builder setDES(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dES_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string DES = 5;</code>
       */
      public Builder clearDES() {
        
        dES_ = getDefaultInstance().getDES();
        onChanged();
        return this;
      }
      /**
       * <code>string DES = 5;</code>
       */
      public Builder setDESBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        dES_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:IOMsg)
    }

    // @@protoc_insertion_point(class_scope:IOMsg)
    private static final IOMsgOuterClass.IOMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new IOMsgOuterClass.IOMsg();
    }

    public static IOMsgOuterClass.IOMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<IOMsg>
        PARSER = new com.google.protobuf.AbstractParser<IOMsg>() {
      public IOMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new IOMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<IOMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<IOMsg> getParserForType() {
      return PARSER;
    }

    public IOMsgOuterClass.IOMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IOMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IOMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013IOMsg.proto\"M\n\005IOMsg\022\013\n\003CMD\030\001 \001(\021\022\014\n\004T" +
      "YPE\030\002 \001(\021\022\016\n\006STATUS\030\003 \001(\021\022\014\n\004BODY\030\004 \001(\t\022" +
      "\013\n\003DES\030\005 \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_IOMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_IOMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IOMsg_descriptor,
        new java.lang.String[] { "CMD", "TYPE", "STATUS", "BODY", "DES", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
